# 선문대학교 컴퓨터공학부
# 2022243101 최완우

### 사는 지역 : 충청남도 천안시
### 1. 파일이름 : 'Cheonan_Temp.csv'

### 1.1 데이터 읽어오기

In [10]:
import pandas as pd

data = pd.read_csv('Cheonan_Temp.csv', encoding = 'cp949')
data

               년월     지점  평균기온(℃)  평균최저기온(℃)  평균최고기온(℃)
0   \t\t\t2025-01  232.0     -1.3       -6.5        4.4
1   \t\t\t2025-02  232.0     -1.8       -7.8        4.1
2   \t\t\t2025-03  232.0      7.2        0.7       13.8
3   \t\t\t2025-04  232.0     12.8        5.4       20.2
4   \t\t\t2025-05  232.0     16.5       10.4       22.8
5   \t\t\t2025-06  232.0     22.6       17.5       28.2
6   \t\t\t2025-07  232.0     26.7       22.5       31.8
7   \t\t\t2025-08  232.0     26.5       22.6       31.3
8   \t\t\t2025-09  232.0     22.3       18.7       26.8
9   \t\t\t2025-10  232.0     15.9       12.1       20.7
10  \t\t\t2025-11  232.0      7.4        1.3       14.4
11  \t\t\t2025-12  232.0      1.2       -4.1        6.1
12         \t\t\t    NaN      NaN        NaN        NaN

In [ ]:
# 년월 앞에 \t 없애기
data['년월'] = data['년월'].str.replace('\t', '')

         년월     지점  평균기온(℃)  평균최저기온(℃)  평균최고기온(℃)
0   2025-01  232.0     -1.3       -6.5        4.4
1   2025-02  232.0     -1.8       -7.8        4.1
2   2025-03  232.0      7.2        0.7       13.8
3   2025-04  232.0     12.8        5.4       20.2
4   2025-05  232.0     16.5       10.4       22.8
5   2025-06  232.0     22.6       17.5       28.2
6   2025-07  232.0     26.7       22.5       31.8
7   2025-08  232.0     26.5       22.6       31.3
8   2025-09  232.0     22.3       18.7       26.8
9   2025-10  232.0     15.9       12.1       20.7
10  2025-11  232.0      7.4        1.3       14.4
11  2025-12  232.0      1.2       -4.1        6.1
12             NaN      NaN        NaN        NaN

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   년월         13 non-null     str
 1   지점         12 non-null     float64
 2   평균기온(℃)    12 non-null     float64
 3   평균최저기온(℃)  12 non-null     float64
 4   평균최고기온(℃)  12 non-null     float64
 5   날짜         13 non-null     str
dtypes: float64(4), str(2)
memory usage: 756.0 bytes